# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5043d4633c94922ef1a78b759a26f92256bebb2be5f081fb8286a75ab4625c2cc6669ff8e5be788334e6766635c0e4f7b564c9da86965b7524ca1dd5da7b8134

test:
  secret_key_base: bb9197aad8d384572d080602f75821316fce02da62c88965dcebacc7a6a4fc0c5ffd392a80be7530477d0225135c3caa34f01618f08f3a75d8c9b2f445c0c600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
